services:
  frontend:
    image: frontend
    ports:
      - "4200:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - passGen
  passGen:
  passwordGeneratorDb:
    image: mysql:8.0.36
    ports:
      -"3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: dashboard_kanban
    restart: always
    healthcheck:
      test: ["CDM", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      
  