services:
  frontend:
    image: frontend
    ports:
      - "4200:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - dashboard-kanban
  dashboard-kanban:
    image: dashboard-kanban
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://dashboardKanbanDB:3306/dashboard_kanban
      DB_USER: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      - dashboardKanbanDB
  dashboardKanbanDB:
    image: mysql:8.0.36
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: dashboard_kanban
    restart: always
    volumes:
      - ./backend/db.sql:/docker-entrypoint-initdb.d/db.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
volumes:
  mysql_data:
      
